otSerdca/blog/urls.py
from django.urls import path
from .views import GalleryView, index_view, about_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', index_view, name='main'),
    path('gallery/', GalleryView.as_view(), name='gallery'),
    path('about/', about_view, name='about'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

otSerdca/otSerdca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), 

]

otSerdca/blog/models.py
from django.db import models

# Create your models here.


class Gallery(models.Model):
    title = models.TextField(max_length=300)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title


class Photo(models.Model):
    photo = models.ImageField(upload_to='static/blog')
    galleryRelated = models.ForeignKey(Gallery, on_delete=models.CASCADE)


    
    
    

otSerdca/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Gallery, Photo


class GalleryView(ListView):
    model = Gallery
    template_name = 'blog/gallery.html'

def index_view(request):
    return render(request, 'blog/index.html', {})

def about_view(request):
    return render(request, 'blog/about.html')

otSerdca/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}
Контакты - 
{% endblock %}

{% block content %}
<main class="container">

    <h3 class="text-center">Можете обращаться к нам на почту или по номеру телефона.</h3>
    <h3 class="text-center pb-3">Также вы можете написать нам в whatsapp или telegram.</h3>
    <div class="card-group p-4">
        <div class="card" style="width: auto;">
            <div class="card-body">
            <h5 class="card-title">Почта</h5>
            <p class="card-text">otserdtsakserdtsu.77@list.ru</p>
            </div>
        </div>
        <div class="card" style="width: auto;">
            <div class="card-body">
            <h5 class="card-title">Пётр</h5>
            <p class="card-text">+7-987-388-79-73</p>
            </div>
        </div>
        <div class="card" style="width: auto;">
            <div class="card-body">
            <h5 class="card-title">Руслан</h5>
            <p class="card-text">+7-988-102-38-87</p>
            </div>
        </div>
    </div>
    </main>

{% endblock %}

otSerdca/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} От Сердца к Сердцу</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'blog/favicon.ico' %}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <style>
      .gallery_img_div{
        position:relative;
        overflow:hidden;
        padding-bottom:100%;
      }
      #gallery_img {
        position: absolute;
        max-width: 100%;
        top: 50%;
        left: 50%;
        transform: translateX(-50%) translateY(-50%);
      }
      .carousel-item img {
        object-fit: cover; /* Do not scale the image */
        object-position: center; /* Center the image within the element */
        width: 100%;
        max-height: 650px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <header
        class="d-flex flex-wrap justify-content-center py-3 mb-3 border-bottom"
      >
        <a
          href="/"
          class="d-flex align-items-center mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
        >
          <img
            class="bi me-2"
            width="270"
            height="50"
            src="{% static 'blog/logo.svg' %}"
          />
          <use xlink:href="#bootstrap"></use>
        </a>

        <ul class="nav nav-pills">
          <li class="nav-item"><a href="/about" class="nav-link">О нас</a></li>
          <li class="nav-item">
            <a href="/gallery" class="nav-link">Галерея</a>
          </li>
          <li class="nav-item">
            <a href="/about" class="nav-link active" aria-current="page"
              >Хочу помогать/Нужна помощь</a
            >
          </li>
        </ul>
      </header>
    </div>
    {% block content %}{% endblock %}
    <div class="container">
      <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top"
      >
        <p class="col-md-4 mb-0 text-body-secondary">2023 От Сердца к Сердцу</p>

        <a
          href="/"
          class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
        >
          <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"></use>
          </svg>
        </a>

        <ul class="nav col-md-4 justify-content-end">
          <li class="nav-item">
            <a href="/gallery" class="nav-link px-2 text-body-secondary"
              >Галерея</a
            >
          </li>
          <li class="nav-item">
            <a href="/about" class="nav-link px-2 text-body-secondary">О нас</a>
          </li>
        </ul>
      </footer>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
    {% block lightbox %}{% endblock %}
  </body>
</html>

otSerdca/blog/templates/blog/gallery.html
{% extends 'blog/base.html' %}

{% block title %}
Галерея - 
{% endblock %}

{% block content %}

    <main class="container">
      <div class="row"></div>
        {% for gallery in object_list %}
          <h1>{{ gallery.title }}</h1>
            
            <div class="row">
              {% for photo in gallery.photo_set.all %}
                <div class="col-6 col-sm-4 col-md-3 col-lg-2 p-2">
                  <div class="gallery_img_div">
                  <a href="{{ photo.photo.url }}" data-toggle="lightbox" data-gallery="{{ gallery.title }}">
                    <img src="{{ photo.photo.url }}" class="py-2" id=gallery_img >
                  </a>
                </div>
            </div>
              {% endfor %}
            </div>
          <p class="p-2">{{ gallery.description }}</p>
          <hr>
        </div>    
        {% endfor %}
        </div>
      </div>
    </main>
{% endblock %}

{% block lightbox %}
<script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>
{% endblock %}

otSerdca/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
Главная - 
{% endblock %}

{% block content %}
{% load static %}
<main class="container">
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'blog/main1.jpg' %}" class="d-block w-100" alt=""/>
        <div class="container ">
          <div class="carousel-caption text-start bg-dark bg-opacity-50 p-3 mb-2 rounded">
            <h1>Помогать людям с нами - легко</h1>
            <p>Стань волонтером вместе с нами сегодня!</p>
            <a class="btn btn-lg btn-primary" href="/about">Хочу помогать</a>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'blog/main2.jpg' %}" class="d-block w-100" alt=""/>
        <div class="container">
          <div class="carousel-caption text-start bg-dark bg-opacity-50 p-3 mb-2 rounded">
            <h1 class = "shadow-lg" >Помогаем нуждающимся</h1>
            <p>Обратитесь к нам, когда нужна помощь</p>
            <a class="btn btn-lg btn-primary" href="/about">Нужна помощь</a>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'blog/main3.jpg' %}" class="d-block w-100" alt=""/>
        <div class="container">
          <div class="carousel-caption text-start bg-dark bg-opacity-50 p-3 mb-2 rounded">
            <h1 class = "shadow-lg" >Вместе мы сделаем этот мир добрее!</h1>
            <p>Свяжитесь с нами</p>
            <a class="btn btn-lg btn-primary" href="/about">Связаться</a>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <h1 class="text-center p-2">Что мы делаем:</h1>
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-3 d-flex flex-column position-static">
          <h3 class="mb-0">Помощь волонтеров</h3>
          <div class="mb-1 text-body-secondary">Это врачи, юристы, психологи, фотографы, журналисты, пенсионеры, школьники, студенты. Их объединяет то, что они готовы помогать общественной организации, а ещё оказывать профессиональные услуги — то есть то, что умеют лучше всего — тем, кто нуждается и не может себе позволить</div>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img width="200" height="250" src="{% static 'blog/card1.jpg' %}" alt="">
          </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-3 d-flex flex-column position-static">
          <h3 class="mb-0">Услуги</h3>
          <div class="mb-1 text-body-secondary">Социальные пособия, юридические консультации и сопровождение, психологическая помощь — важная часть социальной поддержки нуждающихся. Получить такую помощь могут те, кто испытывает материальную нужду или нужду по здоровью. Чтобы записаться на приём, нужно нажать на кнопку "Нужна помощь"</div>
           </div>
        <div class="col-auto d-none d-lg-block">
          <img width="200" height="250" src="{% static 'blog/card2.jpg' %}" alt="">
        </div>
      </div>
    </div>
  </div>

  <h2 class="text-center p-4">План работы общественной организации «От сердца к сердцу»</h2>
    <ol>
        <li>
            <p class="fw-normal">В 2022 году общественная организация расширяет сферу деятельности как в области реализации социальных проектов и программ, так и в сфере содействия развитию СОНКО в Ставропольском крае и развитию молодежного добровольческого движения в различных сферах деятельности. Мы помогаем делать добро, вовлекаем наших благополучателей в активную добровольческую деятельность; участвуем в реализации проектов и программ молодежной политики.</p>
        </li>
        <li>
            <p class="fw-normal">Приоритетные направления деятельности:</p>
            <ul>
                <li>
                    Это – мой город!» - организация мероприятий и акций для улучшения функционирования и оказания помощи объектам социальной структуры региона КМВ;
                </li>
                <li>
                    «Защита детства» - организация мероприятий и акций в области социального. инклюзивного волонтерства, работа с малообеспеченными семьями и детьми с ограниченными возможностями здоровья;
                </li>
                <li>
                    «Искусство во имя добра» - организация благотворительных концертов, выставок, кинопоказов и т. п;
                </li>
                <li>
                    «Годы-это цветы мудрости» - оказание помощи пожилым людям, социально-медицинская и социально-психологическая помощь; акции в центрах социального обслуживания региона, адресная помощь;
                </li>
                <li>
                    «Объединяем города и страны» - мероприятия в области культурного обмена, всероссийские и международные акции;
                </li>
                <li>
                    «Молодежь - наше завтра» - работа по вовлечению в волонтерскую и добровольческую деятельность молодежи, студентов и школьников, просветительская работа, культурное волонтерство.
                </li>
            </ul>
        </li>
        <li>
          Общественная организация способствует развитию инклюзивного добровольчества; все мероприятия общественной организации организуются в формате «доступной среды»; общественная организация проводит мероприятия по вовлечению инвалидов в активную деятельность, инклюзивные центры, инклюзивные фестивали, инклюзивные проекты.
        </li>
        <li>
          Общественная организация содействует развитию добровольческой деятельности и организации эффективной работы СОНКО Ставропольского края:
        </li>
        <ul>
          <li>
            Систематизация нормативной документации;
          </li>
          <li>
            Формирование волонтерских сообществ в различных сферах деятельности;
          </li>
          <li>
            Обучение основам социального проектирования и эффективной реализации проектов;
          </li>
          <li>
            Создание социальных лифтов для добровольцев;
          </li>
          <li>
            Формирование и развитие системы наставничества
          </li>

        </ul>
        <li>
          Общественная организация разрабатывает собственные проекты и программы для реализации их в содружестве с краевыми НКО и общественными объединениями.
        </li>
        <li>
          Общественная организация способствует объединению и реализации совместных проектов между НКО Ставропольского края, образованию волонтерского содружества;
        </li>
        <li>
          Общественная организация активно развивает фандрайзинговые технологии по вовлечению в работу бизнес-сообщества и привлечению благотворителей;
        </li>
        <li>
          Общественная организация проводит мероприятия по улучшению взаимодействия и образованию содружества «ТРЕТЬЕГО СЕКТОРА» и активных граждан;
        </li>
        <li>
          Общественная организация активно участвует в грантовой и форумной кампании с целью привлечения средств на реализацию проектов, получения иных видов поддержки проектов и программ.
        </li>
        <li>
          Общественная организация проводит мероприятия по повышению уровня образования руководства, сотрудников и волонтеров, формирует систему социальных лифтов;
        </li>
        <li>
          Общественная организация активно участвует в общественной жизни региона КМВ и Ставропольского края.
        </li>
        <li>
          Деятельность общественной организации является открытой для широкой общественности и привлечения творческих. человеческих и материальных ресурсов для ее осуществления.
        </li>
    </ol>

  </main>
{% endblock %}